spring:
  application:
    name: User-Module
  datasource:
         password: root
         url: jdbc:mysql://65.0.184.77:3307/accountsdb
         username: root
  jpa:
     database-platform: org.hibernate.dialect.MySQLDialect
     hibernate:
        ddl-auto: update
     show-sql: true 
    
server:
   port : 1001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  level:
    com:
      plan : INFO

