spring:
  application:
    name: User-Module
  datasource:
         password: root
         url: jdbc:mysql://43.205.101.87:3307/userdb
         username: root
  jpa:
     database-platform: org.hibernate.dialect.MySQLDialect
     hibernate:
        ddl-auto: update
     show-sql: true 
    
server:
   port : 1001
eureka:
  client:
    service-url:
      defaultZone: http://43.205.101.87:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  level:
    com:
      plan : INFO

